services:
  api-docs:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./docs:/usr/share/nginx/html:ro
      - ./docs/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    container_name: dragons-counter-docs